### ISSUE TITLE
is subclass responsibility is not highlighted

### ISSUE THREAD

**Issue by pglvdm** [symphonytool/symphony#208]

**Comment by joey-coleman** [comment]
Minimal example — the "is", "responsibility", and "end" keywords are not highlighted (and should be :)

```
class Device = begin
operations
  op : () ==> ()
  op() == is subclass responsibility
end
```

**Comment by lausdahl** [comment]
It seems like the keyword has been commented out:

https://github.com/symphonytool/symphony/blob/development/ide/ui/src/main/java/eu/compassresearch/ide/ui/editor/syntax/CmlKeywords.java

it is only the 'reservedwords' that are highlighted.

The problem with 'end' seems to be related to EOF because it always highlights when a space is added

**Comment by lausdahl** [comment]
fixed this in overture: overturetool/overture@ff4347371cb56ea754de98704a0a546d0f23866e
