### ISSUE TITLE
Backend of POG should use "@" instead of "&" in Symphony

### ISSUE THREAD

**Issue by pglvdm** [symphonytool/symphony#221]
This seems to be an issue when the quick check POG is invoked for all quantified expressions and comprehensions

**Comment by ldcouto** [comment]
The issue is actually broader than that. CML POs are represented with a VDM AST. They are shown to the user with each node's toString() method which has the VDM characters (such as '&')  hardcoded.

The way to fix this is with a CML pretty printer visitor. Doable but time consuming given the size of the tree. For the purpose of discharging POs, of course, this makes no difference.

**Comment by ldcouto** [comment]
I've implemented a temporary workaround that does string replacements of '&' with '@'. The commit is d5b1854.
Not ideal but should be good enough for now.
