### ISSUE TITLE
POG quantifying too many times over function parameters

### ISSUE THREAD

**Issue by ldcouto** [symphonytool/symphony#259]
Given a function:

```
f:int->int
f(x)== 5/x
pre x <>0
```

You will get a PO that quantifies twice over x: `forall x @ forall x ...`. Presumably the POG is looking at the pre_f arguments and quantifying them, uselessly.

**Comment by ldcouto** [comment]
Fixed in overturetool/overture@660a972

**Comment by joey-coleman** [comment]
It looks like there are six PO tests in symphony that fail due to the removal of duplicated quatifications (and probably just need their results regenerated):

`e.c.p.tests.BasicTest`:
- FuncPostCondition.cml
- FunctionApply.cml
- Subtype_Inv.cml

`e.c.p.tests.ModelsTest`:
- AllThePOs.cml
- Dwarf.cml
- GM-06.cml

**Comment by ldcouto** [comment]
Good catch. I'll take care of it tomorrow. Been stuck traveling all day.

**Comment by ldcouto** [comment]
Turns out I had fixed this (7941c13 and 3cb4c69)  but did not push it. Closing again.
